# -*- coding: utf-8 -*-
"""suc_translate_textfile_llamacpp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTY587Ku2dl6Q7Mvj2Hs-WLA9_NXfNNp
"""







!wget https://huggingface.co/mradermacher/Riva-Translate-4B-Instruct-i1-GGUF/resolve/main/Riva-Translate-4B-Instruct.i1-Q6_K.gguf

!wget https://github.com/ggml-org/llama.cpp/releases/download/b7411/llama-b7411-bin-ubuntu-x64.zip

!unzip llama-b7411-bin-ubuntu-x64.zip

!./build/bin/llama-cli -h

!./build/bin/llama-cli -m /content/Riva-Translate-4B-Instruct.i1-Q6_K.gguf -p "translate into arabic welcome"

!./build/bin/llama-cli -m /content/Riva-Translate-4B-Instruct.i1-Q6_K.gguf -p "### Instruction:\nTranslate the word 'Welcome' into Arabic.\n\n### Response:" -n 50

Translate the phrase "This commit restore the previous behavior and add an option to force its activation." into Arabic.

!./build/bin/llama-cli -m /content/Riva-Translate-4B-Instruct.i1-Q6_K.gguf -p "English: Welcome\nArabic:" -n 20

"""لترجمة نص طويل باستخدام llama-cli، لا ينصح بوضع النص داخل الأمر مباشرة (داخل علامة التنصيص " ") لأن سطر الأوامر (Terminal) له حدود، كما أن النص الطويل يحتاج لإعدادات خاصة لضمان عدم انقطاع الترجمة.

إليك أفضل طريقة لترجمة النصوص الطويلة:
1. تجهيز ملف التوجيه (Prompt File)

بدلاً من كتابة النص في التيرمينال، قم بإنشاء ملف نصي جديد (مثلاً سمِّه translate_request.txt) وضع فيه ما يلي:
code Text

    
### Instruction:
Translate the following English text into Arabic accurately.

### Input:
(الصق النص الإنجليزي الطويل هنا...)

### Response:

  

2. تشغيل الأمر مع الإعدادات الصحيحة

عليك استخدام "رايات" (Flags) إضافية لضمان أن الموديل يستوعب النص الطويل ويكمل الترجمة للنهاية:

    -f: لقراءة الملف بدلاً من كتابة النص.

    -c: (Context) لزيادة مساحة الذاكرة المؤقتة للنص (مثلاً 4096).

    -n: عدد الكلمات التي يولدها الموديل (استخدم -1 لتركه يكمل حتى النهاية).

الأمر المقترح:
code Bash

    
!./build/bin/llama-cli -m /content/Riva-Translate-4B-Instruct.i1-Q6_K.gguf -f translate_request.txt -c 4096 -n -1

  

شرح الإعدادات:

    -f translate_request.txt: يقرأ التوجيه والنص من الملف الذي أنشأته، مما يسهل التعامل مع الفقرات الكبيرة.

    -c 4096: هذا الرقم مهم جداً. افتراضياً قد يكون السياق 512 فقط. للنصوص الطويلة، يجب رفعه (2048 أو 4096) ليستوعب النص الأصلي + الترجمة.

    -n -1: تعني "لا تتوقف عن الكتابة حتى تنتهي الترجمة". إذا لم تضع هذا، قد تتوقف الترجمة في منتصف الجملة.

ملاحظة هامة للنصوص "الضخمة جداً":

إذا كان النص عبارة عن صفحات كثيرة (مثلاً كتاب كامل)، فإن الموديل لن يستوعبه دفعة واحدة حتى مع رفع الـ -c. في هذه الحالة، يجب عليك تقسيم النص إلى فقرات (Chunks) وترجمة كل فقرة في ملف منفصل أو طلب واحد تلو الآخر.
User
"""

!./build/bin/llama-cli -m /content/Riva-Translate-4B-Instruct.i1-Q6_K.gguf -f translate_request.txt -c 4096 -n -1

ls /usr/share/tesseract-ocr/tessdata/